// frontend/src/components/Turnstile.vue
<template>
  <div ref="el" class="cf-turnstile"></div>
</template>

<script setup lang="ts">
import { ref, onMounted, onBeforeUnmount } from 'vue'

const props = defineProps<{ siteKey?: string; callbackName?: string }>()
const emit = defineEmits<{ (e: 'verified', token: string): void }>()

const siteKey = props.siteKey || (import.meta.env.VITE_TURNSTILE_SITE_KEY as string)
const callbackName = props.callbackName || `utiopiaTs_${Math.random().toString(36).slice(2)}`
const el = ref<HTMLElement | null>(null)
let widgetId: any = null
let intervalId: any = null

function renderWidget() {
  if (!el.value) return
  const ts = (window as any).turnstile
  if (!ts || typeof ts.render !== 'function') return
  try {
    widgetId = ts.render(el.value, {
      sitekey: siteKey,
      callback: (token: string) => emit('verified', token),
    })
  } catch {}
}

onMounted(() => {
  ;(window as any)[callbackName] = (token: string) => emit('verified', token)
  if ((window as any).turnstile?.render) {
    renderWidget()
  } else {
    intervalId = setInterval(() => {
      if ((window as any).turnstile?.render) {
        clearInterval(intervalId)
        intervalId = null
        renderWidget()
      }
    }, 120)
  }
})

onBeforeUnmount(() => {
  if (intervalId) clearInterval(intervalId)
  const ts = (window as any).turnstile
  if (widgetId && ts && typeof ts.remove === 'function') {
    try { ts.remove(widgetId) } catch {}
  }
  delete (window as any)[callbackName]
})
</script>

// frontend/src/components/Turnstile.tsx
import React, { useRef, useEffect } from 'react'

interface TurnstileProps {
  siteKey?: string
  onVerified: (token: string) => void
  className?: string
}

export function Turnstile({ siteKey, onVerified, className }: TurnstileProps) {
  const elementRef = useRef<HTMLDivElement>(null)
  const intervalRef = useRef<number | null>(null)
  let widgetId: any = null

  const actualSiteKey = siteKey || (import.meta.env.VITE_TURNSTILE_SITE_KEY as string)

  const renderWidget = () => {
    if (!elementRef.current) return
    const turnstile = (window as any).turnstile
    if (!turnstile || typeof turnstile.render !== 'function') return
    
    try {
      widgetId = turnstile.render(elementRef.current, {
        sitekey: actualSiteKey,
        callback: (token: string) => onVerified(token),
      })
    } catch (error) {
      console.error('Failed to render Turnstile widget:', error)
    }
  }

  useEffect(() => {
    if ((window as any).turnstile?.render) {
      renderWidget()
    } else {
      intervalRef.current = window.setInterval(() => {
        if ((window as any).turnstile?.render) {
          window.clearInterval(intervalRef.current!)
          intervalRef.current = null
          renderWidget()
        }
      }, 120)
    }

    return () => {
      if (intervalRef.current) window.clearInterval(intervalRef.current)
      const turnstile = (window as any).turnstile
      if (widgetId && turnstile && typeof turnstile.remove === 'function') {
        try { 
          turnstile.remove(widgetId) 
        } catch (error) {
          console.error('Failed to remove Turnstile widget:', error)
        }
      }
    }
  }, [actualSiteKey, onVerified])

  return <div ref={elementRef} className={className} />
}
